# Generated by Django 3.2.9 on 2021-12-16 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='GameType',
        ),
    ]
