# Generated by Django 3.2.9 on 2021-12-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_rename_category_gametype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='type',
            new_name='game_type',
        ),
        migrations.AddField(
            model_name='game',
            name='game_name',
            field=models.CharField(default='Add game name', max_length=50),
            preserve_default=False,
        ),
    ]
