# Generated by Django 3.2.9 on 2021-12-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_auto_20211218_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='creator',
            new_name='gamer',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_name',
            new_name='maker',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_limit',
            new_name='number_of_players',
        ),
        migrations.RenameField(
            model_name='gametype',
            old_name='name',
            new_name='category',
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='add title of game', max_length=50),
            preserve_default=False,
        ),
    ]
